apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  volumes:
    - name: pvc-volume
      persistentVolumeClaim:
        claimName: pvc-volume
  containers:
    - name: web-server
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: pvc-volume
