apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: foo
  name: foo
spec:
  containers:
  - image: nginx
    name: foo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
